#!/usr/bin/env python3
import collections
import pathlib
import random
import subprocess
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from tools.oracle.memory import MemoryOracle, MemoryState


def assemble(oracle, instruction):
    # These fixtures are authored here, never generated by the Nyx decoder.
    backend = oracle.backend
    with tempfile.TemporaryDirectory(prefix="nyx-sp-differential-") as directory:
        path = pathlib.Path(directory)
        (path / "word.S").write_text(".text\n" + instruction + "\n")
        backend._command([backend.compiler, "-c", "-o", str(path / "word.o"), str(path / "word.S")])
        backend._command(
            [
                backend.objcopy,
                "-O",
                "binary",
                "-j",
                ".text",
                str(path / "word.o"),
                str(path / "word.bin"),
            ]
        )
        code = (path / "word.bin").read_bytes()
    if len(code) != 4:
        raise AssertionError("SP fixture must assemble to one original word")
    return code


def evaluate(probe, code, states):
    payload = "".join(
        " ".join(f"{value:x}" for value in (*state.registers, state.sp, state.nzcv)) + "\n"
        for state in states
    )
    result = subprocess.run(
        [probe, code.hex(), "--sp"],
        input=payload,
        text=True,
        capture_output=True,
        timeout=20,
        check=True,
    )
    rows = result.stdout.splitlines()
    if len(rows) != len(states):
        raise AssertionError("SP semantic probe lost states")
    output = []
    for row, state in zip(rows, states):
        values = tuple(int(value, 16) for value in row.split())
        if len(values) != 33:
            raise AssertionError("invalid SP semantic probe response")
        output.append(MemoryState(values[:31], values[32], values[31], state.memory, state.base))
    return output


def independent(oracle, code, states):
    outcomes = oracle.run_many(code, states)
    if not states or len(outcomes) != len(states):
        raise AssertionError("SP oracle produced no evidence or lost states")
    for initial, outcome in zip(states, outcomes):
        if not outcome.completed or outcome.pc_offset != 4 or outcome.fault_address != 0:
            raise AssertionError(
                "arithmetic SP fixture unexpectedly faulted or failed to terminate"
            )
        if outcome.state.memory != initial.memory:
            raise AssertionError("arithmetic SP fixture changed scratch memory")
    return [outcome.state for outcome in outcomes]


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: a64_sp_diff.py PROBE")
    probe = sys.argv[1]
    oracle = MemoryOracle()
    rng = random.Random(0xD0195)
    states = [
        MemoryState(tuple(rng.getrandbits(64) for _ in range(31)), flags << 28, rng.getrandbits(64))
        for flags in range(16)
    ]
    for value in (
        0,
        1,
        (1 << 64) - 1,
        1 << 63,
        (1 << 63) - 1,
        (1 << 32) - 1,
        1 << 31,
        (1 << 31) - 1,
    ):
        states.append(
            MemoryState((value,) * 31, 0, value, bytes(index % 256 for index in range(4096)))
        )
    snippets = []
    for prefix, sp in (("x", "sp"), ("w", "wsp")):
        for operation in ("add", "sub"):
            snippets.extend(
                (family, instruction)
                for family, instruction in [
                    ("sp_source", f"{operation} {prefix}0, {sp}, #1"),
                    ("sp_destination", f"{operation} {sp}, {prefix}0, #1"),
                    ("sp_update", f"{operation} {sp}, {sp}, #16"),
                    ("sp_shifted_immediate", f"{operation} {sp}, {sp}, #4095, lsl #12"),
                    ("sp_flags", f"{operation}s {prefix}0, {sp}, #1"),
                    ("sp_zero_destination", f"{operation}s {prefix}zr, {sp}, #1"),
                ]
            )
        snippets.extend(
            [
                ("sp_move", f"mov {sp}, {prefix}0"),
                ("sp_move", f"mov {prefix}0, {sp}"),
                ("sp_move", f"mov {sp}, {sp}"),
                ("sp_compare", f"cmp {sp}, #0"),
                ("sp_compare", f"cmn {sp}, #1"),
            ]
        )
    counts = collections.Counter()
    for family, instruction in snippets:
        code = assemble(oracle, instruction)
        expected = independent(oracle, code, states)
        actual = evaluate(probe, code, states)
        for index, (nyx, qemu) in enumerate(zip(actual, expected)):
            if nyx != qemu:
                raise AssertionError(f"SP differential mismatch: {instruction}, case {index}")
        counts[family] += len(states)
    mutations = [
        ("add sp, sp, #16", "add x0, sp, #16"),
        ("adds x0, sp, #1", "add x0, sp, #1"),
        ("add wsp, wsp, #16", "add sp, sp, #16"),
    ]
    for original, mutant in mutations:
        expected = independent(oracle, assemble(oracle, original), states)
        actual = evaluate(probe, assemble(oracle, mutant), states)
        if actual == expected:
            raise AssertionError(f"unrefuted SP mutation: {original} -> {mutant}")
    print(
        f"Independent AArch64 SP differential: {sum(counts.values())} states, {len(snippets)} instructions"
    )
    print("Family comparable counts:", dict(sorted(counts.items())))
    print(f"Mutations refuted: {len(mutations)}/{len(mutations)}")
    print("NOT CHECKED: memory-instruction lifting, calls, branches, relocations, FP/SIMD")


if __name__ == "__main__":
    main()
